

export const array = {
  definition:
    "An array is a collection of items stored at contiguous memory locations. The idea is to store multiple items of the same type together. This makes it easier to calculate the position of each element by simply adding an offset to a base value, i.e., the memory location of the first element of the array.",
  explanation:
    "For simplicity, we can think of an array as a flight of stairs where on each step is placed a value (let’s say one of your friends). Here, you can identify the location of any of your friends by simply knowing the count of the step they are on. This makes it easier to calculate the position of each element by simply adding an offset to a base value, i.e., the memory location of the first element of the array (generally denoted by the name of the array). The base value is index 0 and the difference between the two indexes is the offset.",
  whenToUse: [
    "Use arrays when you want to access the items sequentially by their index.",
    "If you need to access items by their index quickly, arrays are an efficient choice.",
    "When you have a collection of data with the same data type (e.g., an array of integers or strings), arrays are a suitable choice.",
    "If you know the size of the collection in advance and it won't change, arrays are a good option because they have a fixed size.",
    "Arrays can be used to implement fundamental data structures like stacks and queues.",
    "Arrays are crucial for many sorting and searching algorithms, like binary search and quicksort.",
    "In lower-level programming, like systems programming or hardware interaction, arrays provide efficient memory access.",
  ],
  questions: [
    {
      title: "Missing Number",
      id:"268",
      difficulty: "Easy",
      question: "https://leetcode.com/problems/missing-number/description/",
      answer: "https://walkccc.me/LeetCode/problems/0268/?h=missing+number",
    },
    {
      title: "Find Majority Element in an Array",
      id:"169",
      difficulty: "Easy",
      question: "https://leetcode.com/problems/majority-element/description/",
      answer: "https://walkccc.me/LeetCode/problems/0169/?h=majority+element",
    },
    {
      title: "Single Number",
      id:"136",
      difficulty: "Easy",
      question: "https://leetcode.com/problems/single-number/",
      answer: "https://walkccc.me/LeetCode/problems/0136/?h=136",
    },
    {
      title: "How Many are small Than the Current Number ",
      id:"1365",
      difficulty: "Easy",
      question: "https://leetcode.com/problems/how-many-numbers-are-smaller-than-the-current-number/",
      answer: "https://walkccc.me/LeetCode/problems/1365/?h=1365",
    },
    {
      title: "Sort Array by Parity",
      id:"905",
      difficulty: "Easy",
      question: "https://leetcode.com/problems/sort-array-by-parity/",
      answer: "https://walkccc.me/LeetCode/problems/0905/?h=905",
    },
    {
      title: "Create Target Array in the Given Order",
      id:"1389",
      difficulty: "Easy",
      question: "https://leetcode.com/problems/create-target-array-in-the-given-order/",
      answer: "https://walkccc.me/LeetCode/problems/1389/?h=1389",
    },
    {
      title: "Replace Elements With Greatest  Element On Right Side",
      id:"1299",
      difficulty: "Easy",
      question: "https://leetcode.com/problems/replace-elements-with-greatest-element-on-right-side/",
      answer: "https://walkccc.me/LeetCode/problems/1299/?h=1299",
    },
    {
      title: "Count negative numbers in a sorted matrix",
      id:"1351",
      difficulty: "Easy",
      question: "https://leetcode.com/problems/count-negative-numbers-in-a-sorted-matrix/",
      answer: "https://walkccc.me/LeetCode/problems/1351/?h=1351",
    },
    {
      title: "The K Weakest Rows in a Matrix ",
      id:"1337",
      difficulty: "Easy",
      question: "https://leetcode.com/problems/the-k-weakest-rows-in-a-matrix/",
      answer: "https://walkccc.me/LeetCode/problems/1337/?h=1337",
    },
    {
      title: "Find Numbers With Even Numbers of Digits",
      id:"1295",
      difficulty: "Easy",
      question: "https://leetcode.com/problems/find-numbers-with-even-number-of-digits/",
      answer: "https://walkccc.me/LeetCode/problems/1295/?h=1295",
    },
    {
      title: "Rotate Array",
      id:"189",
      difficulty: "Medium",
      question: "https://leetcode.com/problems/rotate-array/description/",
      answer: "https://walkccc.me/LeetCode/problems/0189/?h=rotate+array",
    },
    {
      title: "Search in Rotated Sorted Array",
      id:"33",
      difficulty: "Medium",
      question: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
      answer: "https://walkccc.me/LeetCode/problems/0033/?h=33",
    },
    {
      title: "Sort Colors ",
      id:"75",
      difficulty: "Medium",
      question: "https://leetcode.com/problems/sort-colors/",
      answer: "https://walkccc.me/LeetCode/problems/0075/?h=75",
    },
    {
      title: "Increasing Triplet Subsequence ",
      id:"334",
      difficulty: "Medium",
      question: "https://leetcode.com/problems/increasing-triplet-subsequence/",
      answer: "https://walkccc.me/LeetCode/problems/0334/?h=334",
    },
    {
      title: "Partion Equal Subset Sum ",
      id:"416",
      difficulty: "Medium",
      question: "https://leetcode.com/problems/partition-equal-subset-sum/",
      answer: "https://walkccc.me/LeetCode/problems/0416/?h=416",
    },
    {
      title: "Set Matrix Zero",
      id:"73",
      difficulty: "Medium",
      question: "https://leetcode.com/problems/set-matrix-zeroes/",
      answer: "https://walkccc.me/LeetCode/problems/0073/?h=73",
    },
    {
      title: "Game of Life ",
      id:"289",
      difficulty: "Medium",
      question: "https://leetcode.com/problems/game-of-life/",
      answer: "https://walkccc.me/LeetCode/problems/0289/?h=289",
    },
    {
      title: "Shortest Unsorted Continous Subarray ",
      id:"581",
      difficulty: "Medium",
      question: "https://leetcode.com/problems/shortest-unsorted-continuous-subarray/",
      answer: "https://walkccc.me/LeetCode/problems/0581/?h=581",
    },
    {
      title: "Median Of Two sorted arrays",
      id:"4",
      difficulty: "Hard",
      question: "https://leetcode.com/problems/median-of-two-sorted-arrays/",
      answer: "https://walkccc.me/LeetCode/problems/0004/?h=4",
    },
    {
      title: "First Missing Positive",
      id:"41",
      difficulty: "Hard",
      question: "https://leetcode.com/problems/first-missing-positive/",
      answer: "https://walkccc.me/LeetCode/problems/0041/?h=41",
    },
  ],
};

