
export const dynamicprogrammingData = {
    definition: "",
    explanation: "",
    whenToUse: "",
    question: [
        {
            title: "Climbing Stars Problem",
            id:"70",
            difficulty: "Easy",
            question: "https://leetcode.com/problems/climbing-stairs/",
            answer: "https://walkccc.me/LeetCode/problems/0070/?h=70",
        },
        {
            title: "Ugly Number",
            id:"263",
            difficulty: "Easy",
            question: "https://leetcode.com/problems/ugly-number/",
            answer: "https://walkccc.me/LeetCode/problems/0263/?h=263",
        },
        {
            title: "Minimum Path Problem",
            id:"64",
            difficulty: "Easy",
            question: "https://leetcode.com/problems/minimum-path-sum/",
            answer: "https://walkccc.me/LeetCode/problems/0064/?h=64",
        },
        {
            title: "House Robber ",
            id:"198",
            difficulty: "Easy",
            question: "https://leetcode.com/problems/house-robber/",
            answer: "https://walkccc.me/LeetCode/problems/0198/?h=198",
        },
        {
            title: "Longest Palindromic Subsequence ",
            id:"516",
            difficulty: "Easy",
            question: "https://leetcode.com/problems/longest-palindromic-subsequence/",
            answer: "https://walkccc.me/LeetCode/problems/0516/?h=516",
        },
        {
            title: "Coin Change",
            id:"322",
            difficulty: "Easy",
            question: "https://leetcode.com/problems/coin-change/",
            answer: "https://walkccc.me/LeetCode/problems/0322/?h=322",
        },
        {
            title: "Longest Increasing Subsequence ",
            id:"300",
            difficulty: "Easy",
            question: "https://leetcode.com/problems/longest-increasing-subsequence/",
            answer: "https://walkccc.me/LeetCode/problems/0300/?h=300",
        },
        {
            title: "Unique Paths ",
            id:"62",
            difficulty: "Easy",
            question: "https://leetcode.com/problems/unique-paths/",
            answer: "https://walkccc.me/LeetCode/problems/0062/?h=62",
        },
        {
            title: "Unique Binary Search Trees",
            id:"96",
            difficulty: "Easy",
            question: "https://leetcode.com/problems/unique-binary-search-trees/",
            answer: "https://walkccc.me/LeetCode/problems/0096/?h=96",
        },
        {
            title: "Longest Palindromic Substring",
            id:"5",
            difficulty: "Easy",
            question: "https://leetcode.com/problems/longest-palindromic-substring/",
            answer: "https://walkccc.me/LeetCode/problems/0005/?h=5",
        },
        {
            title: "Edit Distance ",
            id:"72",
            difficulty: "Easy",
            question: "https://leetcode.com/problems/edit-distance/",
            answer: "https://walkccc.me/LeetCode/problems/0072/?h=72",
        },
        {
            title: "Word Break ",
            id:"139",
            difficulty: "Easy",
            question: "https://leetcode.com/problems/word-break/",
            answer: "https://walkccc.me/LeetCode/problems/0139/?h=139",
        },
        {
            title: "Longest Valid Parentheses",
            id:"32",
            difficulty: "Easy",
            question: "https://leetcode.com/problems/longest-valid-parentheses/",
            answer: "https://walkccc.me/LeetCode/problems/0032/?h=32",
        },
        {
            title: "Binary Tree Cameras",
            id:"968",
            difficulty: "Easy",
            question: "https://leetcode.com/problems/binary-tree-cameras/",
            answer: "https://walkccc.me/LeetCode/problems/0968/?h=968",
        },
    ],
}